namespace Nuisho.Elifir.Gen
{
    public class HeadCommentGen<Seed>(ICodeGen<Seed> origin)
        : ICodeGen<Seed>
    {
        public IEnumerable<string> Generate(Seed o)
        {
            yield return "// This file was auto generated by Elifir.Gen.";
            yield return "// To regenerate it with the changed Elifir.Gen remove";
            yield return "// the current file and build/rebuild the current project.";
            yield return string.Empty;

            foreach (var line in origin.Generate(o))
                yield return line;
        }
    }
}
